# syncs changes in local code folder to the E12 container

# docker compose syntax version
version: '3.9'
services:
  # django container
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB_NAME=bandmanager-db
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_USER=bandmanager-u
      - POSTGRES_DB_PASSWORD=bandmanager-pw
      - SECRET_KEY=bandmanager-secret-key
      - DEVELOPMENT_MODE=True
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=0.0.0.0

  # database container
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bandmanager-u
      - POSTGRES_PASSWORD=bandmanager-pw
      - POSTGRES_DB=bandmanager-db